# Generated by Django 4.1.3 on 2023-02-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jop', '0002_jop_description_jop_experiance_jop_jop_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
