# Generated by Django 4.1.3 on 2023-02-05 13:19

from django.db import migrations, models
import jop.models


class Migration(migrations.Migration):

    dependencies = [
        ('jop', '0004_jop_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='jop',
            name='image',
            field=models.ImageField(default='', upload_to=jop.models.image_upload),
            preserve_default=False,
        ),
    ]
