# Generated by Django 4.1.3 on 2023-02-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jop', '0005_jop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='jop',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
