# Generated by Django 4.1.3 on 2023-02-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jop', '0008_apply_jop'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='creted_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
