# Generated by Django 4.1.3 on 2023-03-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jop', '0015_jop_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jop',
            name='place',
            field=models.CharField(choices=[('Menofia', 'Menofia'), ('Cairo', 'Cairo'), ('Giza', 'Giza'), ('Tanta', 'Tanta'), ('Mansora', 'Mansora'), ('Kafr Elshek', 'Kafr Elshek'), ('6 Octper', '6 Octper')], max_length=20),
        ),
    ]
