# Generated by Django 4.1.3 on 2023-03-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jop', '0019_alter_comment_jop_alter_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
