# Generated by Django 4.1.3 on 2023-03-28 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jop', '0020_remove_comment_user_comment_name_alter_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(help_text='Write Your Comment...!'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='jop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jop.jop'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
