# Generated by Django 4.1.3 on 2023-03-28 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jop', '0023_rename_date_comment_comment_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='auther',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='mainjop',
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='jop',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='jop.jop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
