# Generated by Django 4.1.3 on 2023-04-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jop', '0031_alter_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
