# Generated by Django 4.1.3 on 2023-04-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jop', '0034_remove_comment_content_comment_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
