# Generated by Django 4.1.3 on 2023-03-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='profile/'),
        ),
    ]
