# Generated by Django 4.1.3 on 2023-03-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='blank-profile-picture.png', null=True, upload_to='profile/'),
        ),
    ]
