# Generated by Django 4.1.3 on 2023-03-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experiance1',
            field=models.CharField(choices=[('SAS Programming Course', 'SAS Programming Course'), ('Java Programming Course', 'Java Programming Course'), ('ITI-Frontend Development', 'ITI-Frontend Development'), ('ITI-Backend Development', 'ITI-Backend Development'), ('ITI-Machine Learning Development', 'ITI-Machine Learning Development'), ('ITI-Graphic Development', 'ITI-Graphic Development'), ('JavaScript Course', 'JavaScript Course'), ('Linux Programming Course', 'Linux Programming Course'), ('C++ Programming Course', 'C++ Programming Course'), ('Python Programming Course', 'Python Programming Course'), ('Introduction to TCP/IP', 'Introduction to TCP/IP'), ('Cisco CCNP Enterprise-ENARSI', 'Cisco CCNP Enterprise-ENARSI')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='experiance2',
            field=models.CharField(choices=[('SAS Programming Course', 'SAS Programming Course'), ('Java Programming Course', 'Java Programming Course'), ('ITI-Frontend Development', 'ITI-Frontend Development'), ('ITI-Backend Development', 'ITI-Backend Development'), ('ITI-Machine Learning Development', 'ITI-Machine Learning Development'), ('ITI-Graphic Development', 'ITI-Graphic Development'), ('JavaScript Course', 'JavaScript Course'), ('Linux Programming Course', 'Linux Programming Course'), ('C++ Programming Course', 'C++ Programming Course'), ('Python Programming Course', 'Python Programming Course'), ('Introduction to TCP/IP', 'Introduction to TCP/IP'), ('Cisco CCNP Enterprise-ENARSI', 'Cisco CCNP Enterprise-ENARSI')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
