# Generated by Django 4.1.3 on 2023-03-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_experiance1_profile_experiance2'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cv',
            field=models.FileField(default='', upload_to='cvProfile/'),
            preserve_default=False,
        ),
    ]
