# Generated by Django 4.1.3 on 2023-05-16 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_profile_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='githublink',
            field=models.URLField(db_index=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedinlink',
            field=models.URLField(db_index=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
