# Generated by Django 4.1.3 on 2023-05-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cv',
            field=models.FileField(default='blank-profile-picture.png', upload_to='cvProfile/'),
        ),
    ]
