# Generated by Django 4.1.3 on 2023-05-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_profile_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(choices=[('Egypt', 'Egypt'), ('Saudi Arabia', 'Saudi Arabia'), ('Emarat', 'Emarat'), ('America', 'America'), ('France', 'France'), ('Germany', 'Germany'), ('Spain', 'Spain'), ('Italy', 'Italy'), ('Russia', 'Russia')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='nationality',
            field=models.CharField(choices=[('Egyption', 'Egyption'), ('Saudi Arabian', 'Saudi Arabian'), ('Emirati', 'Emirati'), ('American', 'American'), ('French', 'French'), ('German', 'German'), ('Spanish', 'Spanish'), ('Italian', 'Italian'), ('Russian', 'Russian')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.AddField(
            model_name='profile',
            name='typejop',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.worktime'),
        ),
    ]
