# Generated by Django 4.1.3 on 2023-05-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_worktime_profile_birthday_profile_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languagename', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='categories',
            field=models.CharField(choices=[('Front-end development', 'Front-end development'), ('Back-end development', 'Back-end development'), ('Full-stack development', 'Full-stack development'), ('Mobile development', 'Mobile development'), ('Data science', 'Data science')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Information Technology', 'Information Technology'), ('Information Science', 'Information Science'), ('General', 'General'), ('Soft', 'Soft'), ('Bio', 'Bio'), ('No department in my faculty', 'No department in my faculty')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='experianceyears',
            field=models.CharField(choices=[('No Experience', 'No Experience'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('More than 5 years of experience', 'More than 5 years of experience')], default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='faculty',
            field=models.CharField(choices=[('Faculty of computer and information', 'Faculty of computer and information'), ('Faculty of Computers and Artificial Intelligence', 'Faculty of Computers and Artificial Intelligence'), ('Faculty of Engineering and Technology', 'Faculty of Engineering and Technology'), ('Faculty of Computer Science and Information Technology', 'Faculty of Computer Science and Information Technology'), ('Faculty of Computers and Artificial Intelligence', 'Faculty of Computers and Artificial Intelligence'), ('Other', 'Other')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='graduationyear',
            field=models.CharField(choices=[('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('I am graduated', 'I am graduated')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='leveleducation',
            field=models.CharField(choices=[('Bachelor Student', 'Bachelor Student'), ('Bachelor Degree', 'Bachelor Degree'), ('Master Degree', 'Master Degree'), ('PHD Degree', 'PHD Degree'), ('No Degree', 'No Degree')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='salary',
            field=models.IntegerField(default=4000),
        ),
        migrations.AddField(
            model_name='profile',
            name='languages',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.languages'),
        ),
    ]
