# Generated by Django 4.1.3 on 2023-05-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_languages_profile_categories_profile_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(max_length=50),
        ),
    ]
