# Generated by Django 4.1.3 on 2023-05-24 16:42

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_profile_languages_alter_profile_typejop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='typejop',
        ),
        migrations.AddField(
            model_name='profile',
            name='languages',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Arabic', 'Arabic'), ('English', 'English'), ('Spanish', 'Spanish'), ('German', 'German'), ('Italian', 'Italian'), ('Frensh', 'Frensh')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='typejop',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Freelanc / Project', 'Freelanc / Project'), ('Intership', 'Intership'), ('Student Activaty', 'Student Activaty'), ('Volunteering', 'Volunteering')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
