# Generated by Django 4.1.3 on 2023-05-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_profile_languages_remove_profile_typejop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
