# Generated by Django 4.1.3 on 2023-06-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='categories',
            field=models.CharField(choices=[('Front-end development', 'Front-end development'), ('Back-end development', 'Back-end development'), ('Full-stack development', 'Full-stack development'), ('Mobile development', 'Mobile development'), ('Data science', 'Data science'), ('Graphic Designer', 'Graphic Designer')], max_length=100),
        ),
    ]
